### ISSUE TITLE
list of trigger commands

### ISSUE THREAD

**Issue by maravento** [trpt/usbdeath#1]
what is the complete list of admitted trigger commands?
and
How I can replace "poweroff" with a... (Disable all other USB devices - only accept 00-usbdeath.rules)
SUBSYSTEMS=="usb", ACTION=="add", ATTR{authorized}="0"
Thanks

**Comment by trpt** [comment]
List is in array `commands_list` inside script, one per line in single quotes, you can add/edit/delete any commands. There is a second option if you do not want to use array and usbdeath script at all to run commands when something triggers rules, in advanced section, `trigger_cmd_...`, you can replace it with your script or whatever you want.

**Comment by maravento** [comment]
thanks
