### ISSUE TITLE
insserv: warning: script 'usbdeath' missing LSB tags and overrides

### ISSUE THREAD

**Issue by maravento** [trpt/usbdeath#2]
Please update script with something like that (# first):
!/bin/bash
BEGIN INIT INFO
Provides:              blabla
Required-Start:    $syslog
Required-Stop:     $syslog
Default-Start:        2 3 4 5
Default-Stop:         0 1 6
Short-Description: blabla
Description:
END INIT INFO

**Comment by trpt** [comment]
Why should I?

**Comment by maravento** [comment]
it was only a suggestion.
